name: Test & codecov
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install

      - run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
